[workspace]
resolver = "2"
members = [
    "shared",
    "exp01",
    "exp02",
    "exp03",
    "exp04",
    "exp05",
    "exp06",
    "exp07",
    "exp08",
    "exp09",
    "exp10",
    "exp11",
    "exp12",
    "exp13",
    "exp14",
    "exp15",
    "exp16",
    "exp17",
    "exp18",
    "exp19",
    "exp20",
    "exp21",
    "exp22",
    "exp23",
    "exp24",
]
